version: "3.4"
services:
  db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  app:
    build: app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - PORT=4000
      - MIX_ENV=${MIX_ENV}
    volumes:
      - type: bind
        source: ./app
        target: /app
    ports:
      - "127.0.0.1:${PORT}:4000"
    depends_on:
      - db
    command:
      - ./run.sh
