version: "3.4"
volumes:
  dev_deps:
  test_deps:
services:
  db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  testdb:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  app:
    build: app
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - PORT=4000
      - MIX_ENV=dev # Our Phoenix app is in dev mode
      - CAS_BASE_URL=${CAS_BASE_URL}
      - CAS_SERVICE_VALIDATE_BASE_URL=${CAS_SERVICE_VALIDATE_BASE_URL}
      - CAS_CALLBACK_URL=${CAS_CALLBACK_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - REGISTRATION_API_URL=${REGISTRATION_API_URL}
      - REGISTRATION_API_USERNAME=${REGISTRATION_API_USERNAME}
      - REGISTRATION_API_PASSWORD=${REGISTRATION_API_PASSWORD}
      - LDAP_HOST=${LDAP_HOST}
      - LDAP_PORT=${LDAP_PORT}
      - LDAP_SSL=${LDAP_SSL}
      - LDAP_USER=${LDAP_USER}
      - LDAP_PASS=${LDAP_PASS}
    volumes:
      - type: bind
        source: ./app
        target: /app
      # Use a volume in the container for our
      # dependencies to keep the separate from
      # the testapp deps.
      - dev_deps:/app/deps/
    ports:
      - "${HOST}:${PORT}:4000"
    depends_on:
      - db
    entrypoint:
      - ./run.sh
    command:
      - server
  tests:
    build: app
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=testdb
      - PORT=4000
      - MIX_ENV=test # Our Phoenix app is in test mode
      - CAS_BASE_URL=${CAS_BASE_URL}
      - CAS_SERVICE_VALIDATE_BASE_URL=${CAS_SERVICE_VALIDATE_BASE_URL}
      - CAS_CALLBACK_URL=${CAS_CALLBACK_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - REGISTRATION_API_URL=${REGISTRATION_API_URL}
      - REGISTRATION_API_USERNAME=${REGISTRATION_API_USERNAME}
      - REGISTRATION_API_PASSWORD=${REGISTRATION_API_PASSWORD}
      - LDAP_HOST=${LDAP_HOST}
      - LDAP_PORT=${LDAP_PORT}
      - LDAP_SSL=${LDAP_SSL}
      - LDAP_USER=${LDAP_USER}
      - LDAP_PASS=${LDAP_PASS}
    volumes:
      - type: bind
        source: ./app
        target: /app
      # Use a volume in the container for our
      # dependencies to keep the separate from
      # the app/dev deps.
      - test_deps:/app/deps/
    depends_on:
      - testdb
    entrypoint:
      - ./run.sh
    command:
      - watch-tests
  mockcas:
    image: yellowtrex/mockcas
    environment:
      - PORT=4000
    ports:
      - "127.0.0.1:${MOCKCAS_PORT}:4000"
