version: "3.4"
volumes:
  prod_deps:
  node_deps:
  letsencrypt:
    external: true
services:
  db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  app:
    build: app
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - PORT=4000
      - MIX_ENV=prod
      - CAS_BASE_URL=${CAS_BASE_URL}
      - CAS_SERVICE_VALIDATE_BASE_URL=${CAS_SERVICE_VALIDATE_BASE_URL}
      - CAS_CALLBACK_URL=${CAS_CALLBACK_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DOMAIN=${DOMAIN}
    volumes:
      - type: bind
        source: ./app
        target: /app
      - prod_deps:/app/deps/
      - node_deps:/app/assets/node_modules
      - letsencrypt:/etc/letsencrypt/
    ports:
      - "0.0.0.0:${PORT}:4000"
    depends_on:
      - db
    entrypoint:
      - ./run.sh
    command:
      - prod-server
  certbot:
    image: certbot/certbot:v1.3.0
    entrypoint: /entrypoint.sh
    volumes:
      - letsencrypt:/etc/letsencrypt/
      - "./certbot/entrypoint.sh:/entrypoint.sh"

