version: "3.4"
volumes:
  dev_deps:
  test_deps:
services:
  db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  testdb:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  app:
    build: app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - PORT=4000
      - MIX_ENV=dev # Our Phoenix app is in dev mode
    volumes:
      - type: bind
        source: ./app
        target: /app
      # Use a volume in the container for our
      # dependencies to keep the separate from
      # the testapp deps.
      - dev_deps:/app/deps/
    ports:
      - "127.0.0.1:${PORT}:4000"
    depends_on:
      - db
    entrypoint:
      - ./run.sh
      - server
  tests:
    build: app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=testdb
      - PORT=4000
      - MIX_ENV=test # Our Phoenix app is in test mode
    volumes:
      - type: bind
        source: ./app
        target: /app
      # Use a volume in the container for our
      # dependencies to keep the separate from
      # the app/dev deps.
      - test_deps:/app/deps/
    depends_on:
      - testdb
    entrypoint:
      - ./run.sh
      - watch-tests
  mockcas:
    image: yellowtrex/mockcas
    environment:
      - PORT=4000
    ports:
      - "127.0.0.1:${MOCKCAS_PORT}:4000"
